// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagement.Infrastructure.Data;

#nullable disable

namespace TaskManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagement.Core.Entities.TaskItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AssignedUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AssignedUserNavId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserNavId");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AssignedUserId = 1L,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 43, 5, 941, DateTimeKind.Utc).AddTicks(2098),
                            Description = "Set up the initial project structure",
                            EndDate = new DateTime(2025, 5, 24, 20, 43, 5, 941, DateTimeKind.Utc).AddTicks(2098),
                            IsCompleted = false,
                            IsDeleted = false,
                            StartDate = new DateTime(2025, 5, 19, 20, 43, 5, 941, DateTimeKind.Utc).AddTicks(2089),
                            Title = "Initialize project",
                            UpdatedAt = new DateTime(2025, 5, 21, 20, 43, 5, 941, DateTimeKind.Utc).AddTicks(2099)
                        },
                        new
                        {
                            Id = 2L,
                            AssignedUserId = 2L,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 43, 5, 941, DateTimeKind.Utc).AddTicks(2104),
                            Description = "Design the database schema",
                            EndDate = new DateTime(2025, 5, 26, 20, 43, 5, 941, DateTimeKind.Utc).AddTicks(2103),
                            IsCompleted = false,
                            IsDeleted = false,
                            StartDate = new DateTime(2025, 5, 20, 20, 43, 5, 941, DateTimeKind.Utc).AddTicks(2103),
                            Title = "Database design",
                            UpdatedAt = new DateTime(2025, 5, 21, 20, 43, 5, 941, DateTimeKind.Utc).AddTicks(2104)
                        });
                });

            modelBuilder.Entity("TaskManagement.Core.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 43, 5, 941, DateTimeKind.Utc).AddTicks(1960),
                            Email = "admin@example.com",
                            FirstName = "System",
                            IsDeleted = false,
                            LastName = "Admin",
                            Password = "Admin@123",
                            UpdatedAt = new DateTime(2025, 5, 21, 20, 43, 5, 941, DateTimeKind.Utc).AddTicks(1962),
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 43, 5, 941, DateTimeKind.Utc).AddTicks(1966),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Doe",
                            Password = "John@123",
                            UpdatedAt = new DateTime(2025, 5, 21, 20, 43, 5, 941, DateTimeKind.Utc).AddTicks(1967),
                            UserName = "johndoe"
                        });
                });

            modelBuilder.Entity("TaskManagement.Core.Entities.TaskItem", b =>
                {
                    b.HasOne("TaskManagement.Core.Entities.User", "AssignedUserNav")
                        .WithMany()
                        .HasForeignKey("AssignedUserNavId");

                    b.Navigation("AssignedUserNav");
                });
#pragma warning restore 612, 618
        }
    }
}
