// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagement.Infrastructure.Data;

#nullable disable

namespace TaskManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagement.Core.Entities.TaskItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AssignedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("AssignedUserId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AssignedUserId = 1L,
                            CreatedAt = new DateTime(2025, 5, 24, 0, 46, 58, 560, DateTimeKind.Utc).AddTicks(9609),
                            Description = "Set up the initial project structure",
                            EndDate = new DateTime(2025, 5, 27, 0, 46, 58, 560, DateTimeKind.Utc).AddTicks(9609),
                            IsCompleted = false,
                            StartDate = new DateTime(2025, 5, 22, 0, 46, 58, 560, DateTimeKind.Utc).AddTicks(9604),
                            Title = "Initialize project",
                            UpdatedAt = new DateTime(2025, 5, 24, 0, 46, 58, 560, DateTimeKind.Utc).AddTicks(9610)
                        },
                        new
                        {
                            Id = 2L,
                            AssignedUserId = 2L,
                            CreatedAt = new DateTime(2025, 5, 24, 0, 46, 58, 560, DateTimeKind.Utc).AddTicks(9612),
                            Description = "Design the database schema",
                            EndDate = new DateTime(2025, 5, 29, 0, 46, 58, 560, DateTimeKind.Utc).AddTicks(9612),
                            IsCompleted = false,
                            StartDate = new DateTime(2025, 5, 23, 0, 46, 58, 560, DateTimeKind.Utc).AddTicks(9612),
                            Title = "Database design",
                            UpdatedAt = new DateTime(2025, 5, 24, 0, 46, 58, 560, DateTimeKind.Utc).AddTicks(9613)
                        },
                        new
                        {
                            Id = 3L,
                            AssignedUserId = 1L,
                            CreatedAt = new DateTime(2025, 5, 24, 0, 46, 58, 560, DateTimeKind.Utc).AddTicks(9614),
                            Description = "Set up user authentication and authorization",
                            EndDate = new DateTime(2025, 5, 31, 0, 46, 58, 560, DateTimeKind.Utc).AddTicks(9614),
                            IsCompleted = false,
                            StartDate = new DateTime(2025, 5, 24, 0, 46, 58, 560, DateTimeKind.Utc).AddTicks(9614),
                            Title = "Implement authentication",
                            UpdatedAt = new DateTime(2025, 5, 24, 0, 46, 58, 560, DateTimeKind.Utc).AddTicks(9615)
                        },
                        new
                        {
                            Id = 4L,
                            AssignedUserId = 2L,
                            CreatedAt = new DateTime(2025, 5, 24, 0, 46, 58, 560, DateTimeKind.Utc).AddTicks(9620),
                            Description = "Develop the necessary API endpoints for the application",
                            EndDate = new DateTime(2025, 6, 3, 0, 46, 58, 560, DateTimeKind.Utc).AddTicks(9619),
                            IsCompleted = false,
                            StartDate = new DateTime(2025, 5, 25, 0, 46, 58, 560, DateTimeKind.Utc).AddTicks(9619),
                            Title = "Create API endpoints",
                            UpdatedAt = new DateTime(2025, 5, 24, 0, 46, 58, 560, DateTimeKind.Utc).AddTicks(9620)
                        });
                });

            modelBuilder.Entity("TaskManagement.Core.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 5, 24, 0, 46, 58, 560, DateTimeKind.Utc).AddTicks(9528),
                            Email = "admin@example.com",
                            FirstName = "System",
                            LastName = "Admin",
                            Password = "Admin@123",
                            UpdatedAt = new DateTime(2025, 5, 24, 0, 46, 58, 560, DateTimeKind.Utc).AddTicks(9530),
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 5, 24, 0, 46, 58, 560, DateTimeKind.Utc).AddTicks(9535),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "John@123",
                            UpdatedAt = new DateTime(2025, 5, 24, 0, 46, 58, 560, DateTimeKind.Utc).AddTicks(9535),
                            UserName = "johndoe"
                        });
                });

            modelBuilder.Entity("TaskManagement.Core.Entities.TaskItem", b =>
                {
                    b.HasOne("TaskManagement.Core.Entities.User", "AssignedUserNav")
                        .WithMany("TaskItems")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TaskItem_User_AssignedUserId");

                    b.Navigation("AssignedUserNav");
                });

            modelBuilder.Entity("TaskManagement.Core.Entities.User", b =>
                {
                    b.Navigation("TaskItems");
                });
#pragma warning restore 612, 618
        }
    }
}
